apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalProvider
metadata:
  name: katan-openai-provider
  namespace: llm
spec:
  provider: openai
  endpoint: 3-13-21-181.sslip.io
  auth:
    secretRef:
      name: llm-katan-creds
---
apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalProvider
metadata:
  name: katan-vertex-provider
  namespace: llm
spec:
  provider: vertex-openai
  endpoint: 3-13-21-181.sslip.io
  auth:
    secretRef:
      name: llm-katan-vertex-openai-creds
