name: Check Typos

on:
  pull_request: {}
  push: {}

jobs:
  typos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check typos
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
