name: Check Typos

on:
  pull_request: {}
  push: {}

jobs:
  typos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check typos
        uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53 # v1.50.2
